# Generated by Django 5.2.16 on 2026-08-02 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("user_agent", models.TextField(blank=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("os", models.CharField(blank=True, max_length=100)),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("referrer", models.URLField(blank=True)),
                ("landing_page", models.URLField(blank=True)),
                ("exit_page", models.URLField(blank=True)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=0, help_text="Session duration in seconds"
                    ),
                ),
                ("page_views", models.PositiveIntegerField(default=0)),
                ("source", models.CharField(blank=True, max_length=50)),
                ("medium", models.CharField(blank=True, max_length=50)),
                ("campaign", models.CharField(blank=True, max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics",
                "verbose_name_plural": "Analytics",
                "db_table": "analytics",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ip_address"], name="analytics_ip_addr_a43cee_idx"
                    ),
                    models.Index(
                        fields=["session_id"], name="analytics_session_ee319b_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_created_786169_idx"
                    ),
                    models.Index(
                        fields=["country"], name="analytics_country_3ad16d_idx"
                    ),
                ],
            },
        ),
    ]
