# Generated by Django 5.2.16 on 2026-08-02 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Timeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("title", models.CharField(db_index=True, max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("education", "Education"),
                            ("work", "Work Experience"),
                            ("project", "Project"),
                            ("achievement", "Achievement"),
                            ("certification", "Certification"),
                            ("milestone", "Milestone"),
                            ("other", "Other"),
                        ],
                        default="milestone",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("description", models.TextField(blank=True)),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional event details"
                    ),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="timeline/"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, help_text="Icon class", max_length=50),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Hex color code", max_length=7
                    ),
                ),
                ("show_on_homepage", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timeline Event",
                "verbose_name_plural": "Timeline Events",
                "db_table": "timeline_events",
                "ordering": ["-date", "order"],
                "indexes": [
                    models.Index(fields=["date"], name="timeline_ev_date_5c301e_idx"),
                    models.Index(
                        fields=["event_type"], name="timeline_ev_event_t_a263b2_idx"
                    ),
                    models.Index(
                        fields=["status", "is_active"],
                        name="timeline_ev_status_0d4e8b_idx",
                    ),
                ],
            },
        ),
    ]
