# Generated by Django 5.2.16 on 2026-08-02 19:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project_categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="seo/og/"),
                ),
                ("canonical_url", models.URLField(blank=True)),
                (
                    "no_index",
                    models.BooleanField(
                        default=False,
                        help_text="Prevent search engines from indexing this page",
                    ),
                ),
                (
                    "no_follow",
                    models.BooleanField(
                        default=False,
                        help_text="Prevent search engines from following links",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="projects/thumbnails/"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="projects/covers/"
                    ),
                ),
                ("short_description", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField()),
                (
                    "problem",
                    models.TextField(blank=True, help_text="Problem statement"),
                ),
                (
                    "solution",
                    models.TextField(blank=True, help_text="Solution provided"),
                ),
                (
                    "architecture",
                    models.TextField(blank=True, help_text="Architecture details"),
                ),
                ("role", models.CharField(blank=True, max_length=100)),
                ("client", models.CharField(blank=True, max_length=100)),
                ("company", models.CharField(blank=True, max_length=100)),
                (
                    "duration",
                    models.CharField(
                        blank=True, help_text="e.g., 3 months", max_length=50
                    ),
                ),
                ("team_size", models.PositiveIntegerField(blank=True, null=True)),
                ("responsibilities", models.TextField(blank=True)),
                ("programming_language", models.CharField(blank=True, max_length=100)),
                ("framework", models.CharField(blank=True, max_length=100)),
                ("database", models.CharField(blank=True, max_length=100)),
                ("api", models.CharField(blank=True, max_length=100)),
                ("authentication", models.CharField(blank=True, max_length=100)),
                ("deployment", models.CharField(blank=True, max_length=100)),
                ("github_url", models.URLField(blank=True)),
                ("live_demo_url", models.URLField(blank=True)),
                ("documentation_url", models.URLField(blank=True)),
                ("figma_url", models.URLField(blank=True)),
                ("case_study_url", models.URLField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_pinned", models.BooleanField(db_index=True, default=False)),
                ("challenges", models.TextField(blank=True)),
                ("future_improvements", models.TextField(blank=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("share_count", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="project_categories.projectcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "projects",
                "ordering": ["-is_pinned", "-is_featured", "order", "-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="projects_slug_25ccba_idx"),
                    models.Index(
                        fields=["status", "is_active"],
                        name="projects_status_5b3350_idx",
                    ),
                    models.Index(
                        fields=["visibility", "is_featured"],
                        name="projects_visibil_442b03_idx",
                    ),
                    models.Index(
                        fields=["category"], name="projects_categor_c363bc_idx"
                    ),
                ],
            },
        ),
    ]
