# Generated by Django 5.2.16 on 2026-08-02 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("issuer", models.CharField(db_index=True, max_length=255)),
                (
                    "credential_id",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("issue_date", models.DateField()),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="Leave blank if no expiration", null=True
                    ),
                ),
                (
                    "does_not_expire",
                    models.BooleanField(
                        default=False, help_text="Certificate does not expire"
                    ),
                ),
                (
                    "verification_url",
                    models.URLField(blank=True, help_text="URL to verify certificate"),
                ),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("description", models.TextField(blank=True)),
                (
                    "skills",
                    models.JSONField(
                        blank=True, default=list, help_text="List of skills certified"
                    ),
                ),
                (
                    "certificate_image",
                    models.ImageField(blank=True, null=True, upload_to="certificates/"),
                ),
                (
                    "issuer_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="certificates/issuers/"
                    ),
                ),
                ("badge_url", models.URLField(blank=True, help_text="Badge image URL")),
                ("certificate_url", models.URLField(blank=True)),
                ("show_on_homepage", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "db_table": "certifications",
                "ordering": ["-is_featured", "-issue_date", "order"],
                "indexes": [
                    models.Index(
                        fields=["issuer"], name="certificati_issuer_27b631_idx"
                    ),
                    models.Index(
                        fields=["credential_id"], name="certificati_credent_9efe90_idx"
                    ),
                    models.Index(
                        fields=["issue_date"], name="certificati_issue_d_fe5aff_idx"
                    ),
                    models.Index(
                        fields=["status", "is_active"],
                        name="certificati_status_16ef14_idx",
                    ),
                    models.Index(
                        fields=["is_verified"], name="certificati_is_veri_4bd6cb_idx"
                    ),
                ],
            },
        ),
    ]
