# Generated by Django 5.1.15 on 2026-10-02 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Article Tag',
                'verbose_name_plural': 'Article Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(help_text="Unique slug identifier (e.g. 'django-postgresql-performance')", max_length=150, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(db_index=True, default='Backend Architecture', max_length=100)),
                ('date', models.CharField(blank=True, default='', help_text='Display date string', max_length=50)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], db_index=True, default='Published', max_length=20)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('excerpt', models.TextField(help_text='Short abstract/summary for cards and search')),
                ('content', models.TextField(help_text='Full markdown article content')),
                ('header_image', models.CharField(blank=True, default='', max_length=500)),
                ('author_name', models.CharField(default='Manoj Khatri', max_length=100)),
                ('author_role', models.CharField(default='Backend Software Engineer', max_length=100)),
                ('read_time_minutes', models.PositiveIntegerField(default=5)),
                ('tags_list', models.JSONField(blank=True, default=list, help_text='Cached list of tag names for rapid JSON response')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='blog.articletag')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
