# Generated by Django 5.2.16 on 2026-08-02 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="seo/og/"),
                ),
                ("canonical_url", models.URLField(blank=True)),
                (
                    "no_index",
                    models.BooleanField(
                        default=False,
                        help_text="Prevent search engines from indexing this page",
                    ),
                ),
                (
                    "no_follow",
                    models.BooleanField(
                        default=False,
                        help_text="Prevent search engines from following links",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "availability_badge",
                    models.CharField(
                        blank=True, help_text="e.g., Available for work", max_length=50
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("busy", "Busy"),
                            ("offline", "Offline"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="hero/profile/"),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="hero/background/"
                    ),
                ),
                (
                    "resume_button_text",
                    models.CharField(default="Download Resume", max_length=50),
                ),
                ("resume_button_url", models.URLField(blank=True)),
                (
                    "hire_me_button_text",
                    models.CharField(default="Hire Me", max_length=50),
                ),
                ("hire_me_button_url", models.URLField(blank=True)),
                (
                    "github_button_text",
                    models.CharField(default="GitHub", max_length=50),
                ),
                ("github_button_url", models.URLField(blank=True)),
                (
                    "linkedin_button_text",
                    models.CharField(default="LinkedIn", max_length=50),
                ),
                ("linkedin_button_url", models.URLField(blank=True)),
                (
                    "email_button_text",
                    models.CharField(default="Email Me", max_length=50),
                ),
                ("email_button_url", models.EmailField(blank=True, max_length=254)),
                (
                    "whatsapp_button_text",
                    models.CharField(default="WhatsApp", max_length=50),
                ),
                ("whatsapp_button_url", models.URLField(blank=True)),
                (
                    "typing_animation_texts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of texts for typing animation",
                    ),
                ),
                ("typing_animation_enabled", models.BooleanField(default=True)),
                ("show_on_homepage", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Sections",
                "db_table": "hero_sections",
                "ordering": ["order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "is_active"],
                        name="hero_sectio_status_49ae5f_idx",
                    ),
                    models.Index(
                        fields=["show_on_homepage"],
                        name="hero_sectio_show_on_24c4c9_idx",
                    ),
                ],
            },
        ),
    ]
