# Generated by Django 5.2.17 on 2026-08-15 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="hero",
            index=models.Index(
                fields=["status", "show_on_homepage", "is_active"],
                name="hero_sectio_status_edf7af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hero",
            index=models.Index(
                fields=["is_featured"], name="hero_sectio_is_feat_964b1d_idx"
            ),
        ),
    ]
