# Generated by Django 5.2.16 on 2026-08-02 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="seo/og/"),
                ),
                ("canonical_url", models.URLField(blank=True)),
                (
                    "no_index",
                    models.BooleanField(
                        default=False,
                        help_text="Prevent search engines from indexing this page",
                    ),
                ),
                (
                    "no_follow",
                    models.BooleanField(
                        default=False,
                        help_text="Prevent search engines from following links",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("tagline", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(blank=True, help_text="Icon class", max_length=50),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="services/"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fixed", "Fixed Price"),
                            ("hourly", "Hourly Rate"),
                            ("project", "Project Based"),
                            ("custom", "Custom Quote"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True, default=list, help_text="List of service features"
                    ),
                ),
                (
                    "process_steps",
                    models.JSONField(
                        blank=True, default=list, help_text="List of process steps"
                    ),
                ),
                ("show_on_homepage", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "db_table": "services",
                "ordering": ["-is_featured", "order"],
                "indexes": [
                    models.Index(fields=["slug"], name="services_slug_ffd546_idx"),
                    models.Index(
                        fields=["status", "is_active"],
                        name="services_status_f5532d_idx",
                    ),
                    models.Index(
                        fields=["is_featured"], name="services_is_feat_f920c3_idx"
                    ),
                ],
            },
        ),
    ]
