# Generated by Django 5.1.15 on 2026-10-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(help_text="Unique slug identifier (e.g. 'backend-engineering', 'api-architecture')", max_length=100, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('icon', models.CharField(default='Server', max_length=100)),
                ('short_summary', models.TextField()),
                ('detailed_scope', models.TextField(blank=True, default='')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature bullet points')),
                ('deliverables', models.JSONField(blank=True, default=list, help_text='List of tangible deliverables')),
                ('technologies', models.JSONField(blank=True, default=list, help_text='Relevant technologies list')),
                ('visibility', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], db_index=True, default='Published', max_length=20)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('cover_image', models.CharField(blank=True, default='', max_length=500)),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
    ]
