# Generated by Django 5.2.16 on 2026-08-02 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_projects", models.PositiveIntegerField(default=0)),
                ("published_projects", models.PositiveIntegerField(default=0)),
                ("draft_projects", models.PositiveIntegerField(default=0)),
                ("total_visitors", models.PositiveIntegerField(default=0)),
                ("unique_visitors", models.PositiveIntegerField(default=0)),
                ("total_contacts", models.PositiveIntegerField(default=0)),
                ("pending_contacts", models.PositiveIntegerField(default=0)),
                ("total_downloads", models.PositiveIntegerField(default=0)),
                ("resume_downloads", models.PositiveIntegerField(default=0)),
                ("total_blogs", models.PositiveIntegerField(default=0)),
                ("published_blogs", models.PositiveIntegerField(default=0)),
                ("total_skills", models.PositiveIntegerField(default=0)),
                ("total_certifications", models.PositiveIntegerField(default=0)),
                ("total_subscribers", models.PositiveIntegerField(default=0)),
                ("active_subscribers", models.PositiveIntegerField(default=0)),
                ("stats_date", models.DateField(db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Stats",
                "verbose_name_plural": "Dashboard Stats",
                "db_table": "dashboard_stats",
                "ordering": ["-stats_date"],
                "indexes": [
                    models.Index(
                        fields=["stats_date"], name="dashboard_s_stats_d_0657a5_idx"
                    )
                ],
            },
        ),
    ]
