# Generated by Django 5.2.16 on 2026-07-26 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("github_id", models.BigIntegerField(db_index=True, unique=True)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("bio", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("company", models.CharField(blank=True, max_length=255)),
                ("blog", models.URLField(blank=True)),
                ("avatar_url", models.URLField()),
                ("followers", models.PositiveIntegerField(default=0)),
                ("following", models.PositiveIntegerField(default=0)),
                ("public_repos", models.PositiveIntegerField(default=0)),
                ("public_gists", models.PositiveIntegerField(default=0)),
                ("created_at_github", models.DateTimeField()),
                ("updated_at_github", models.DateTimeField()),
                ("html_url", models.URLField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Profile",
                "verbose_name_plural": "GitHub Profiles",
                "db_table": "github_profile",
            },
        ),
        migrations.CreateModel(
            name="GitHubRepository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("repository_id", models.BigIntegerField(db_index=True, unique=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("full_name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("language", models.CharField(blank=True, max_length=100)),
                ("primary_language", models.CharField(blank=True, max_length=100)),
                ("languages", models.JSONField(blank=True, default=dict)),
                ("stars", models.PositiveIntegerField(default=0)),
                ("forks", models.PositiveIntegerField(default=0)),
                ("watchers", models.PositiveIntegerField(default=0)),
                ("open_issues", models.PositiveIntegerField(default=0)),
                ("size", models.PositiveIntegerField(default=0)),
                ("created_at_github", models.DateTimeField()),
                ("updated_at_github", models.DateTimeField()),
                ("pushed_at", models.DateTimeField()),
                ("html_url", models.URLField()),
                ("clone_url", models.URLField()),
                ("homepage", models.URLField(blank=True)),
                ("is_private", models.BooleanField(default=False)),
                ("is_fork", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_disabled", models.BooleanField(default=False)),
                ("topics", models.JSONField(blank=True, default=list)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Repository",
                "verbose_name_plural": "GitHub Repositories",
                "db_table": "github_repositories",
                "ordering": [
                    "-is_featured",
                    "display_order",
                    "-stars",
                    "-updated_at_github",
                ],
            },
        ),
        migrations.CreateModel(
            name="GitHubContribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contribution_type",
                    models.CharField(
                        choices=[
                            ("commit", "Commit"),
                            ("pr", "Pull Request"),
                            ("issue", "Issue"),
                            ("review", "Code Review"),
                            ("release", "Release"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField(db_index=True)),
                ("url", models.URLField(blank=True)),
                ("number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="github.githubrepository",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Contribution",
                "verbose_name_plural": "GitHub Contributions",
                "db_table": "github_contributions",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="githubrepository",
            index=models.Index(
                fields=["repository_id"], name="github_repo_reposit_164a36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="githubrepository",
            index=models.Index(
                fields=["is_featured", "display_order"],
                name="github_repo_is_feat_bf7537_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="githubcontribution",
            index=models.Index(fields=["date"], name="github_cont_date_1e7bff_idx"),
        ),
        migrations.AddIndex(
            model_name="githubcontribution",
            index=models.Index(
                fields=["contribution_type"], name="github_cont_contrib_99b0b5_idx"
            ),
        ),
    ]
