# Generated by Django 5.2.16 on 2026-08-02 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="seo/og/"),
                ),
                ("canonical_url", models.URLField(blank=True)),
                (
                    "no_index",
                    models.BooleanField(
                        default=False,
                        help_text="Prevent search engines from indexing this page",
                    ),
                ),
                (
                    "no_follow",
                    models.BooleanField(
                        default=False,
                        help_text="Prevent search engines from following links",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="about/photo/"),
                ),
                ("bio", models.TextField(blank=True)),
                ("long_description", models.TextField(blank=True)),
                ("mission", models.TextField(blank=True)),
                ("vision", models.TextField(blank=True)),
                ("years_experience", models.PositiveIntegerField(default=0)),
                ("projects_completed", models.PositiveIntegerField(default=0)),
                ("happy_clients", models.PositiveIntegerField(default=0)),
                ("awards_won", models.PositiveIntegerField(default=0)),
                ("quote", models.TextField(blank=True)),
                ("quote_author", models.CharField(blank=True, max_length=255)),
                (
                    "highlights",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of key highlights/achievements",
                    ),
                ),
                ("show_on_homepage", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "About Section",
                "verbose_name_plural": "About Sections",
                "db_table": "about_sections",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "is_active"],
                        name="about_secti_status_d3d596_idx",
                    ),
                    models.Index(
                        fields=["show_on_homepage"],
                        name="about_secti_show_on_1cbc74_idx",
                    ),
                ],
            },
        ),
    ]
