# Generated by Django 5.1.15 on 2026-10-02 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentItem',
            fields=[
                ('id', models.CharField(help_text="Unique slug key (e.g. 'ats-resume-builder', 'portfolio-drf-backend')", max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('researching', 'Researching')], db_index=True, default='active', max_length=50)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Completion percentage (0-100)')),
                ('related_project_id', models.CharField(blank=True, default='', max_length=100)),
                ('since', models.CharField(default='', max_length=50)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Currently Building Item',
                'verbose_name_plural': 'Currently Building Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.CharField(default='main', help_text="Single-instance primary key ('main')", max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Manoj Khatri', max_length=150)),
                ('title', models.CharField(default='Backend Software Engineer', max_length=200)),
                ('tagline', models.CharField(default='Backend systems engineered for scale, security, and long-term reliability.', max_length=255)),
                ('bio', models.JSONField(blank=True, default=list, help_text='Array of bio paragraphs')),
                ('photo', models.CharField(default='/images/manoj.jpg', max_length=500)),
                ('location', models.CharField(default='Kathmandu, Nepal', max_length=150)),
                ('email', models.EmailField(default='manojkc1dev@gmail.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+977 9842203976', max_length=50)),
                ('availability', models.CharField(default='Open to remote freelance & junior backend roles', max_length=200)),
                ('resume_url', models.CharField(default='/resume.pdf', max_length=500)),
                ('hero_badge', models.CharField(blank=True, default='', max_length=150)),
                ('hero_title', models.CharField(blank=True, default='', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True, default='')),
                ('primary_cta', models.CharField(blank=True, default='', max_length=100)),
                ('secondary_cta', models.CharField(blank=True, default='', max_length=100)),
                ('pillars', models.JSONField(blank=True, default=list, help_text='Core engineering pillars (title, description, focus)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profiles',
            },
        ),
        migrations.CreateModel(
            name='UseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Uses Category',
                'verbose_name_plural': 'Uses Categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProfileStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stat_id', models.CharField(help_text="Unique slug key, e.g. 'projects', 'speedup'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('subtext', models.CharField(blank=True, default='', max_length=150)),
                ('icon_name', models.CharField(default='Code2', max_length=50)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_items', to='siteconfig.siteprofile')),
            ],
            options={
                'verbose_name': 'Profile Stat',
                'verbose_name_plural': 'Profile Stats',
                'ordering': ['order', 'stat_id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('icon', models.CharField(default='Github', max_length=50)),
                ('handle', models.CharField(blank=True, default='', max_length=100)),
                ('visible', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials_items', to='siteconfig.siteprofile')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('why', models.TextField()),
                ('link', models.URLField(blank=True, default='', max_length=500)),
                ('tag', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='siteconfig.usecategory')),
            ],
            options={
                'verbose_name': 'Uses Item',
                'verbose_name_plural': 'Uses Items',
                'ordering': ['order', 'name'],
            },
        ),
    ]
