# Generated by Django 5.1.15 on 2026-10-02 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(help_text="Unique kebab-case slug identifier matching frontend (e.g., 'agritech')", max_length=100, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(db_index=True, default='backend', max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='live', max_length=50)),
                ('visibility', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], db_index=True, default='Published', max_length=20)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('image', models.CharField(blank=True, default='', max_length=500)),
                ('thumbnail', models.CharField(blank=True, default='', max_length=500)),
                ('highlights', models.JSONField(blank=True, default=list, help_text='List of 3-5 highlight bullet strings')),
                ('tech', models.JSONField(blank=True, default=list, help_text='List of technology names')),
                ('languages', models.JSONField(blank=True, default=list, help_text='List of programming languages')),
                ('links', models.JSONField(blank=True, default=dict, help_text='Links dictionary: live, github, caseStudy, apiDocs, etc.')),
                ('gallery', models.JSONField(blank=True, default=list, help_text='Screenshot image paths')),
                ('proof', models.JSONField(blank=True, default=list, help_text='Proof badges list')),
                ('what_i_built', models.JSONField(blank=True, default=list)),
                ('lessons_learned', models.JSONField(blank=True, default=list)),
                ('related_projects', models.JSONField(blank=True, default=list)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('duration', models.CharField(blank=True, default='', max_length=100)),
                ('client', models.CharField(blank=True, default='', max_length=255)),
                ('industry', models.CharField(blank=True, default='', max_length=255)),
                ('year_duration', models.CharField(blank=True, default='', max_length=100)),
                ('short_description', models.TextField(blank=True, default='')),
                ('full_case_study', models.TextField(blank=True, default='')),
                ('live_url', models.URLField(blank=True, default='', max_length=500)),
                ('github_url', models.URLField(blank=True, default='', max_length=500)),
                ('case_study_url', models.CharField(blank=True, default='', max_length=255)),
                ('api_docs_url', models.URLField(blank=True, default='', max_length=500)),
                ('key_highlights', models.TextField(blank=True, default='')),
                ('problem', models.TextField(blank=True, default='')),
                ('solution', models.TextField(blank=True, default='')),
                ('architecture', models.TextField(blank=True, default='', help_text='Mermaid.js diagram definition string')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('problem', models.TextField()),
                ('approach', models.TextField()),
                ('outcome', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_items', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Project Challenge',
                'verbose_name_plural': 'Project Challenges',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, choices=[('speed', 'Speed'), ('users', 'Users'), ('db', 'Database'), ('payment', 'Payment'), ('uptime', 'Uptime')], default='speed', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_items', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Project Metric',
                'verbose_name_plural': 'Project Metrics',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TechChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layer', models.CharField(max_length=100)),
                ('choice', models.CharField(max_length=255)),
                ('why', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_choices_items', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Tech Choice',
                'verbose_name_plural': 'Tech Choices',
                'ordering': ['order', 'id'],
            },
        ),
    ]
