# Generated by Django 5.2.16 on 2026-08-02 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("title", models.CharField(db_index=True, max_length=255)),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("award", "Award"),
                            ("recognition", "Recognition"),
                            ("milestone", "Milestone"),
                            ("publication", "Publication"),
                            ("speaking", "Speaking Engagement"),
                            ("other", "Other"),
                        ],
                        default="award",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField(db_index=True)),
                ("organization", models.CharField(blank=True, max_length=255)),
                ("organization_url", models.URLField(blank=True)),
                (
                    "organization_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="achievements/organizations/"
                    ),
                ),
                (
                    "certificate_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="achievements/certificates/"
                    ),
                ),
                ("badge_url", models.URLField(blank=True)),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Link to achievement details"
                    ),
                ),
                ("show_on_homepage", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "db_table": "achievements",
                "ordering": ["-is_featured", "-date", "order"],
                "indexes": [
                    models.Index(fields=["date"], name="achievement_date_3628c5_idx"),
                    models.Index(
                        fields=["achievement_type"],
                        name="achievement_achieve_813271_idx",
                    ),
                    models.Index(
                        fields=["status", "is_active"],
                        name="achievement_status_7a1c24_idx",
                    ),
                    models.Index(
                        fields=["is_featured"], name="achievement_is_feat_ab0b7e_idx"
                    ),
                ],
            },
        ),
    ]
