# Generated by Django 5.2.16 on 2026-08-02 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TechStackCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("language", "Programming Language"),
                            ("framework", "Framework"),
                            ("library", "Library"),
                            ("database", "Database"),
                            ("cloud", "Cloud Service"),
                            ("devops", "DevOps Tool"),
                            ("tool", "Tool"),
                            ("testing", "Testing Tool"),
                            ("ai", "AI/ML"),
                            ("data", "Data Science"),
                        ],
                        default="tool",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tech Stack Category",
                "verbose_name_plural": "Tech Stack Categories",
                "db_table": "tech_stack_categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TechStackItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "icon",
                    models.CharField(blank=True, help_text="Icon class", max_length=50),
                ),
                ("svg", models.TextField(blank=True, help_text="SVG code")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="techstack/"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Hex color code", max_length=7
                    ),
                ),
                ("official_website", models.URLField(blank=True)),
                ("documentation_url", models.URLField(blank=True)),
                (
                    "skill_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("show_on_homepage", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="techstack.techstackcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tech Stack Item",
                "verbose_name_plural": "Tech Stack Items",
                "db_table": "tech_stack_items",
                "ordering": ["-is_featured", "display_order", "order"],
            },
        ),
        migrations.AddIndex(
            model_name="techstackcategory",
            index=models.Index(fields=["slug"], name="tech_stack__slug_010756_idx"),
        ),
        migrations.AddIndex(
            model_name="techstackcategory",
            index=models.Index(
                fields=["category_type"], name="tech_stack__categor_1b6dcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="techstackitem",
            index=models.Index(fields=["slug"], name="tech_stack__slug_dc6b4d_idx"),
        ),
        migrations.AddIndex(
            model_name="techstackitem",
            index=models.Index(
                fields=["category"], name="tech_stack__categor_fb4b71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="techstackitem",
            index=models.Index(
                fields=["status", "is_active"], name="tech_stack__status_ccc58e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="techstackitem",
            index=models.Index(
                fields=["is_featured"], name="tech_stack__is_feat_bc6d7e_idx"
            ),
        ),
    ]
