# Generated by Django 5.2.17 on 2026-08-15 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techstack", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="techstackitem",
            index=models.Index(
                fields=["status", "show_on_homepage", "is_active"],
                name="tech_stack__status_e5c4df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="techstackitem",
            index=models.Index(
                fields=["skill_level"], name="tech_stack__skill_l_b60c36_idx"
            ),
        ),
    ]
