# Generated by Django 5.2.16 on 2026-08-02 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("client_name", models.CharField(db_index=True, max_length=255)),
                ("client_designation", models.CharField(blank=True, max_length=255)),
                ("client_company", models.CharField(blank=True, max_length=255)),
                (
                    "client_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="testimonials/photos/"
                    ),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="testimonials/logos/"
                    ),
                ),
                ("review", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(default=5, help_text="Rating out of 5"),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("project_name", models.CharField(blank=True, max_length=255)),
                ("project_url", models.URLField(blank=True)),
                ("show_on_homepage", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "db_table": "testimonials",
                "ordering": ["-is_featured", "order"],
                "indexes": [
                    models.Index(
                        fields=["client_name"], name="testimonial_client__1d46b2_idx"
                    ),
                    models.Index(
                        fields=["client_company"], name="testimonial_client__e671b1_idx"
                    ),
                    models.Index(
                        fields=["status", "is_active"],
                        name="testimonial_status_e5701c_idx",
                    ),
                    models.Index(
                        fields=["is_featured"], name="testimonial_is_feat_554925_idx"
                    ),
                ],
            },
        ),
    ]
