# Generated by Django 5.1.15 on 2026-10-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.CharField(help_text="Unique slug identifier (e.g., 'sajha-infotech', 'tu-bit')", max_length=100, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('company_url', models.URLField(blank=True, default='', max_length=500)),
                ('period', models.CharField(help_text="Display date range, e.g. 'Jul 2024 – Dec 2024'", max_length=100)),
                ('start', models.CharField(blank=True, default='', max_length=50)),
                ('end', models.CharField(blank=True, default='present', max_length=50)),
                ('location', models.CharField(default='Kathmandu, Nepal', max_length=150)),
                ('type', models.CharField(choices=[('fulltime', 'Full Time'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('education', 'Education')], db_index=True, default='fulltime', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('bullets', models.JSONField(blank=True, default=list, help_text='List of achievement bullet points')),
                ('tech', models.JSONField(blank=True, default=list, help_text='List of technologies used')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
