# Generated by Django 5.2.16 on 2026-08-02 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("company", models.CharField(db_index=True, max_length=255)),
                ("position", models.CharField(db_index=True, max_length=255)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("freelance", "Freelance"),
                            ("internship", "Internship"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if currently working",
                        null=True,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, help_text="Currently working here"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("responsibilities", models.TextField(blank=True)),
                (
                    "technologies",
                    models.JSONField(
                        blank=True, default=list, help_text="List of technologies used"
                    ),
                ),
                (
                    "achievements",
                    models.JSONField(
                        blank=True, default=list, help_text="List of key achievements"
                    ),
                ),
                ("company_website", models.URLField(blank=True)),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="experience/companies/"
                    ),
                ),
                ("show_on_homepage", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
                "db_table": "experiences",
                "ordering": ["-is_current", "-start_date", "order"],
                "indexes": [
                    models.Index(
                        fields=["company"], name="experiences_company_ab072a_idx"
                    ),
                    models.Index(
                        fields=["position"], name="experiences_positio_67159f_idx"
                    ),
                    models.Index(
                        fields=["start_date"], name="experiences_start_d_1f1fe3_idx"
                    ),
                    models.Index(
                        fields=["status", "is_active"],
                        name="experiences_status_2673e3_idx",
                    ),
                ],
            },
        ),
    ]
