# Generated by Django 5.1.15 on 2026-10-02 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('has_whatsapp', models.BooleanField(default=True)),
                ('scope_title', models.CharField(blank=True, default='Website Contact Inquiry', max_length=255)),
                ('budget_range', models.CharField(blank=True, default='Standard Project', max_length=100)),
                ('timeline', models.CharField(blank=True, default='Flexible', max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Won', 'Won')], db_index=True, default='New', max_length=50)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('replied', models.BooleanField(db_index=True, default=False)),
                ('project_id', models.CharField(blank=True, help_text='Referenced project slug', max_length=100, null=True)),
                ('project_title', models.CharField(blank=True, default='', max_length=255)),
                ('project_tag', models.CharField(blank=True, default='', max_length=100)),
                ('source_page', models.CharField(blank=True, default='', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
