# Generated by Django 5.1.15 on 2026-10-02 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.CharField(help_text="Unique slug identifier (e.g., 'backend', 'databases')", max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SkillItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(blank=True, default='', max_length=100)),
                ('highlight', models.BooleanField(db_index=True, default=False)),
                ('proficiency', models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Learning', 'Learning')], default='Advanced', max_length=50)),
                ('level', models.CharField(choices=[('learning', 'Learning'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='advanced', max_length=50)),
                ('years', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.skillcategory')),
            ],
            options={
                'verbose_name': 'Skill Item',
                'verbose_name_plural': 'Skill Items',
                'ordering': ['order', 'name'],
            },
        ),
    ]
