# Generated by Django 5.2.17 on 2026-08-15 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["status", "show_on_homepage", "is_active"],
                name="skills_status_470f72_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["percentage"], name="skills_percent_922429_idx"),
        ),
    ]
