# Generated by Django 5.1.15 on 2026-10-02 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeDataRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_tag', models.CharField(default='Production-2026', max_length=50)),
                ('target_headline', models.CharField(default='Backend Software Engineer (Python / Django / PostgreSQL)', max_length=255)),
                ('summary_text', models.TextField(blank=True, default='')),
                ('resume_url', models.CharField(default='/resume.pdf', max_length=500)),
                ('file_name', models.CharField(default='Manoj_KC_Backend_Resume.pdf', max_length=255)),
                ('customization', models.JSONField(blank=True, default=dict, help_text='ATS Customization parameters: templateStyle, fontFamily, accentColor, spacingDensity, paperFormat, pageLayout, etc.')),
                ('sections_data', models.JSONField(blank=True, default=list, help_text='Array of ResumeSection objects with items, bullets, and badge tags')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume Data Record',
                'verbose_name_plural': 'Resume Data Records',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(default='Manoj_KC_Resume.pdf', max_length=255)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('file_binary', models.BinaryField(blank=True, help_text='Direct binary payload backup', null=True)),
                ('version_tag', models.CharField(blank=True, default='v1.0', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resume Document',
                'verbose_name_plural': 'Resume Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
