# Generated by Django 5.2.16 on 2026-08-02 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("institution", models.CharField(db_index=True, max_length=255)),
                ("degree", models.CharField(db_index=True, max_length=255)),
                ("major", models.CharField(blank=True, max_length=255)),
                ("field_of_study", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if currently studying",
                        null=True,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, help_text="Currently studying"),
                ),
                (
                    "cgpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cumulative Grade Point Average",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overall percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=10)),
                ("description", models.TextField(blank=True)),
                (
                    "coursework",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of relevant coursework",
                    ),
                ),
                (
                    "achievements",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of academic achievements",
                    ),
                ),
                ("institution_website", models.URLField(blank=True)),
                (
                    "institution_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="education/institutions/"
                    ),
                ),
                ("show_on_homepage", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
                "db_table": "education",
                "ordering": ["-is_current", "-end_date", "-start_date", "order"],
                "indexes": [
                    models.Index(
                        fields=["institution"], name="education_institu_c1016a_idx"
                    ),
                    models.Index(fields=["degree"], name="education_degree_236c60_idx"),
                    models.Index(
                        fields=["start_date"], name="education_start_d_7c751f_idx"
                    ),
                    models.Index(
                        fields=["status", "is_active"],
                        name="education_status_6f45c9_idx",
                    ),
                ],
            },
        ),
    ]
