# Generated by Django 5.2.17 on 2026-08-15 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="education",
            index=models.Index(
                fields=["status", "show_on_homepage", "is_active"],
                name="education_status_514539_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="education",
            index=models.Index(
                fields=["is_current", "start_date"], name="education_is_curr_987200_idx"
            ),
        ),
    ]
