# Generated by Django 5.2.17 on 2026-08-15 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(
                fields=["status", "is_active", "published_at"],
                name="blogs_status_d335eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(fields=["author"], name="blogs_author__ac6a34_idx"),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(fields=["created_at"], name="blogs_created_7b53fa_idx"),
        ),
    ]
