# Generated by Django 5.2.16 on 2026-08-02 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SEOSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("site_title", models.CharField(default="Portfolio", max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="seo/og/"),
                ),
                ("og_title", models.CharField(blank=True, max_length=255)),
                ("og_description", models.TextField(blank=True)),
                (
                    "twitter_card",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("summary_large_image", "Summary Large Image"),
                            ("app", "App"),
                            ("player", "Player"),
                        ],
                        default="summary",
                        max_length=20,
                    ),
                ),
                (
                    "twitter_image",
                    models.ImageField(blank=True, null=True, upload_to="seo/twitter/"),
                ),
                ("twitter_title", models.CharField(blank=True, max_length=255)),
                ("twitter_description", models.TextField(blank=True)),
                ("canonical_url", models.URLField(blank=True)),
                (
                    "robots_txt",
                    models.TextField(blank=True, help_text="Robots.txt content"),
                ),
                ("schema_org_type", models.CharField(default="Person", max_length=50)),
                (
                    "schema_org_json",
                    models.JSONField(
                        blank=True, default=dict, help_text="Schema.org JSON-LD data"
                    ),
                ),
                ("sitemap_enabled", models.BooleanField(default=True)),
                ("google_analytics_id", models.CharField(blank=True, max_length=50)),
                ("google_tag_manager_id", models.CharField(blank=True, max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Settings",
                "verbose_name_plural": "SEO Settings",
                "db_table": "seo_settings",
            },
        ),
    ]
