import type {
  AdminProject,
  AdminService,
  AdminArticle,
  AdminInquiry,
  HomepageContentState,
  AboutContentState,
  ContactPricingState,
  FooterContentState,
  LogoManagementState,
  CompanyIdentityState,
  SocialProfile,
  GlobalSettingsState,
  ResumeData,
  ResumeSection,
  ResumeItem,
} from './types';

export const initialProjects: AdminProject[] = [
  {
    id: 'agritech',
    title: 'Agritech | Agriculture Marketplace Platform',
    slug: 'agritech',
    category: 'Full-Stack / Marketplace',
    status: 'Deployed',
    visibility: 'Published',
    featured: true,
    thumbnail: '/images/agritech.png',
    client: 'AgriTech Nepal (Farmers & Buyers)',
    industry: 'Agriculture & E-Commerce',
    yearDuration: '2026 · 3 Months',
    shortDescription: 'Multi-vendor marketplace with JWT-secured APIs, KYC onboarding, live price negotiation, cart/order pipeline, and Khalti/eSewa payment integration.',
    fullCaseStudy: 'Architected and implemented a secure role-based marketplace (farmers vs buyers) with JWT authentication, custom KYC verification workflows, real-time negotiation inquiries, and payment processing via Khalti and eSewa APIs.',
    liveUrl: 'https://agritech-marketplace.onrender.com/',
    githubUrl: 'https://github.com/manojkc1dev/AgriTech_Marketplace',
    caseStudyUrl: '/projects/agritech',
    technologies: ['Python', 'Django', 'DRF', 'PostgreSQL', 'React', 'Tailwind CSS', 'Docker'],
    languages: ['Python', 'TypeScript', 'SQL'],
    keyHighlights: 'Complete negotiation pipeline with contact-sharing alerts, dual payment gateways (Khalti + eSewa), and Docker-ready deployment (Gunicorn + WhiteNoise).',
    metrics: [
      { label: 'API Response Time', value: '~30% faster API', icon: 'speed' },
      { label: 'Payment Settlement', value: 'Khalti + eSewa', icon: 'payment' },
      { label: 'Catalog Scale', value: '10K+ records', icon: 'db' },
      { label: 'Service Availability', value: '99.9% uptime', icon: 'uptime' },
    ],
    proof: [
      'live-demo',
      'public-repo',
      'readme',
      'tests',
      'ci-passing',
      'deployed',
      'api-docs',
      'docker',
      'postman-collection',
    ],
  },
  {
    id: 'calcpro',
    title: 'CalcPro | Multi-Functional Web Calculator',
    slug: 'calcpro',
    category: 'Web Application & Utilities',
    status: 'In Production',
    visibility: 'Published',
    featured: true,
    thumbnail: '/images/calcpro.png',
    client: 'Personal Project',
    industry: 'Developer Tools & Mathematics',
    yearDuration: '2025 · 1 Month',
    shortDescription: 'Full-stack calculator with Basic, Scientific, Programmer & Financial modes powered by a DRF expression evaluator.',
    fullCaseStudy: 'Engineered a DRF-backed mathematical expression evaluator with zero-downtime deployment on Render. Features mobile-first responsive interfaces and high-precision float calculation safety.',
    liveUrl: 'https://calcpro-calculator.onrender.com/',
    githubUrl: 'https://github.com/manojkc1dev/calcpro-calculator/',
    caseStudyUrl: '/projects/calcpro',
    technologies: ['Django REST Framework', 'React', 'Vite', 'JavaScript', 'Render'],
    languages: ['Python', 'JavaScript'],
    keyHighlights: 'Zero-downtime Render deployment, safe mathematical parsing via DRF REST API, and 4 specialized calculation modes.',
    metrics: [
      { label: 'Calculation Modes', value: '4 modes', icon: 'speed' },
      { label: 'Deployment Uptime', value: 'Zero-downtime deploy', icon: 'uptime' },
    ],
    proof: ['live-demo', 'public-repo', 'readme', 'deployed'],
  },
  {
    id: 'auth-sentinel',
    title: 'AuthSentinel | Django JWT & RBAC Boilerplate',
    slug: 'auth-sentinel',
    category: 'Developer Tools & Microservices',
    status: 'In Production',
    visibility: 'Published',
    featured: true,
    thumbnail: '',
    client: 'Open Source / Internal Tooling',
    industry: 'Cybersecurity & Auth Systems',
    yearDuration: '2026 · Ongoing',
    shortDescription: 'Modular Django authentication microservice template featuring rotating JWTs, granular role-based permissions, and Redis token blacklisting.',
    fullCaseStudy: 'Engineered a production-ready authentication and authorization microservice featuring dual access/refresh tokens, Redis-backed blacklist revocation, custom permission decorators, and structured audit logs.',
    liveUrl: 'https://github.com/manojkc1dev',
    githubUrl: 'https://github.com/manojkc1dev',
    caseStudyUrl: '/projects/auth-sentinel',
    technologies: ['Python', 'Django', 'Redis', 'Docker', 'PostgreSQL'],
    languages: ['Python', 'SQL'],
    keyHighlights: 'Rotating JWT token architecture with Redis blacklisting, custom RBAC permission classes, and automated test suite.',
    metrics: [
      { label: 'Token Invalidation', value: 'Redis blacklist', icon: 'speed' },
      { label: 'Access Security', value: 'Granular RBAC', icon: 'users' },
      { label: 'Test Coverage', value: '100% auth suites', icon: 'uptime' },
    ],
    proof: ['public-repo', 'readme', 'docker', 'tests'],
  },
  {
    id: 'paystream-gateway',
    title: 'PayStream | Unified Nepal Payment Hub (Khalti & eSewa)',
    slug: 'paystream-gateway',
    category: 'Fintech & Payment Gateways',
    status: 'In Production',
    visibility: 'Published',
    featured: true,
    thumbnail: '',
    client: 'Fintech & Commercial Platforms',
    industry: 'Financial Technology',
    yearDuration: '2026 · 2 Months',
    shortDescription: 'Dedicated payment microservice handling signature verification, asynchronous transaction reconciliation, and HMAC validation for eSewa and Khalti v2.',
    fullCaseStudy: 'Architected an idempotent payment gateway aggregator supporting both eSewa EPAY v2 (HMAC-SHA256 signature verification) and Khalti v2 REST APIs with automated reconciliation retries and webhook integrity auditing.',
    liveUrl: 'https://agritech-marketplace.onrender.com/',
    githubUrl: 'https://github.com/manojkc1dev',
    caseStudyUrl: '/projects/paystream-gateway',
    technologies: ['Python', 'Django REST Framework', 'Celery', 'Redis', 'PostgreSQL', 'Docker'],
    languages: ['Python', 'SQL'],
    keyHighlights: 'Strict idempotent transactions preventing double charges, dual payment integrations, and Celery asynchronous webhook retry queue.',
    metrics: [
      { label: 'API Response Time', value: '~30% faster API', icon: 'speed' },
      { label: 'Payment Settlement', value: 'Khalti + eSewa', icon: 'payment' },
      { label: 'Webhook Latency', value: 'Sub-180ms verify', icon: 'uptime' },
      { label: 'Reconciliation', value: '100% idempotent', icon: 'db' },
    ],
    proof: ['live-demo', 'public-repo', 'readme', 'api-docs', 'docker', 'deployed'],
  },
  {
    id: 'shabdhabhandar',
    title: 'Shabdhabhandar | English-to-Nepali Dictionary',
    slug: 'shabdhabhandar',
    category: 'Search & NLP Systems',
    status: 'In Production',
    visibility: 'Published',
    featured: true,
    thumbnail: '/images/shabdhabhandar.png',
    client: 'Personal Project',
    industry: 'Linguistics & Education',
    yearDuration: '2025 · 2 Months',
    shortDescription: 'Unicode-aware bilingual dictionary with 10,000+ entries, fault-tolerant search, automated ingestion, and scheduled Word of the Day.',
    fullCaseStudy: 'Developed an automated ingestion pipeline for 10,000+ English and Devanagari Unicode dictionary entries. Implemented fault-tolerant fuzzy lookups, session search histories, and background daily scheduler tasks.',
    liveUrl: 'https://sabdhabhandar.onrender.com/',
    githubUrl: 'https://github.com/manojkc1dev/sabdhabhandar/',
    caseStudyUrl: '/projects/shabdhabhandar',
    technologies: ['Python', 'Django', 'SQLite', 'JavaScript', 'Render'],
    languages: ['Python', 'JavaScript', 'SQL'],
    keyHighlights: 'Handles 10,000+ bilingual entries with sub-50ms query responses, full Unicode Devanagari support, and automated daily word scheduling.',
    metrics: [
      { label: 'Corpus Volume', value: '10K+ entries', icon: 'db' },
      { label: 'Search Latency', value: 'Sub-200ms search', icon: 'speed' },
    ],
    proof: ['live-demo', 'public-repo', 'readme', 'deployed'],
  },
  {
    id: 'acadflow',
    title: 'AcadFlow | Student Management System',
    slug: 'acadflow',
    category: 'Academic ERP & Systems',
    status: 'Completed',
    visibility: 'Published',
    featured: true,
    thumbnail: '/images/acadflow.png',
    client: 'Tribhuvan University (BIT Capstone)',
    industry: 'Higher Education',
    yearDuration: '2024 · 5 Months',
    shortDescription: 'Solo-built student management system for BIT final year with role-based auth, attendance/grade tracking, and server-side PDF exports.',
    fullCaseStudy: 'Designed and shipped an end-to-end academic management system as the BIT undergraduate capstone project. Included multi-tier user authentication (students, instructors, administration), automated attendance registers, and dynamic PDF report cards via ReportLab.',
    liveUrl: 'https://acadflow-sms.onrender.com/',
    githubUrl: 'https://github.com/manojkc1dev/AcadFlow_SMS',
    caseStudyUrl: '/projects/acadflow',
    technologies: ['Python', 'Django', 'PostgreSQL', 'ReportLab (PDF)', 'HTML5', 'CSS3'],
    languages: ['Python', 'SQL', 'HTML', 'CSS'],
    keyHighlights: 'Solo-engineered capstone receiving top marks; automated server-side PDF generation and zero data inconsistency across academic semesters.',
    metrics: [
      { label: 'Role Architecture', value: '3 roles', icon: 'users' },
      { label: 'Export Engine', value: 'PDF export', icon: 'db' },
    ],
    proof: ['public-repo', 'readme'],
  },
  {
    id: 'nepal-geodata-api',
    title: 'Nepal GeoData | Administrative Boundaries API',
    slug: 'nepal-geodata-api',
    category: 'Open Source / Geographic Services',
    status: 'In Production',
    visibility: 'Published',
    featured: true,
    thumbnail: '',
    client: 'Nepal Developer Community',
    industry: 'Geospatial & Public Data',
    yearDuration: '2025 · 1 Month',
    shortDescription: 'High-performance open-source REST API delivering provinces, districts, and municipalities data with spatial query caching and GeoJSON output.',
    fullCaseStudy: 'Built an open data API service providing hierarchical administrative units across Nepal. Optimized with in-memory caching for sub-15ms response times, and full Swagger/OpenAPI documentation.',
    liveUrl: 'https://sabdhabhandar.onrender.com/',
    githubUrl: 'https://github.com/manojkc1dev',
    caseStudyUrl: '/projects/nepal-geodata-api',
    technologies: ['Python', 'Django REST Framework', 'PostgreSQL', 'Docker'],
    languages: ['Python', 'SQL'],
    keyHighlights: 'Nested JSON and GeoJSON outputs for 7 provinces and 77 districts with in-memory caching.',
    metrics: [
      { label: 'Cache Latency', value: 'Sub-15ms cache', icon: 'speed' },
      { label: 'Geographic Scale', value: '7 Prov · 77 Dist', icon: 'db' },
      { label: 'Coverage', value: '753 Local Units', icon: 'uptime' },
      { label: 'Data Formats', value: 'REST + GeoJSON', icon: 'speed' },
    ],
    proof: ['public-repo', 'readme', 'api-docs', 'docker', 'deployed'],
  },
];

export const initialServices: AdminService[] = [
  {
    id: 'srv-1',
    order: 1,
    title: 'Backend API Engineering (Django & DRF)',
    slug: 'backend-api-engineering',
    icon: 'Server',
    shortSummary: 'High-performance, modular REST APIs built with Django REST Framework, clean architecture, and OpenAPI/Postman documentation.',
    detailedScope: 'Designing scalable backend APIs using Django REST Framework, custom model viewsets, serializers, pagination, filter backends, and decoupled business logic designed for clean frontend and mobile handoff.',
    features: [
      'Clean Django App Modular Architecture',
      'DRF Serializers & Custom Field Validation',
      'Filterable & Searchable DefaultRouters',
      'Comprehensive Postman Collections & Swagger',
    ],
    deliverables: [
      'Production Docker Compose & Gunicorn Setup',
      'Documented API Endpoints with Request/Response Contracts',
      'Automated Django Unit Tests',
    ],
    technologies: ['Python', 'Django', 'Django REST Framework', 'Docker'],
    visibility: 'Published',
    featured: true,
  },
  {
    id: 'srv-2',
    order: 2,
    title: 'Database Modeling & Query Optimization',
    slug: 'database-modeling-optimization',
    icon: 'Database',
    shortSummary: 'Relational database schema modeling in PostgreSQL, query indexing, eliminating N+1 queries, and achieving ~30% latency reduction.',
    detailedScope: 'Schema normalization, composite B-Tree indexes, query execution profiling using EXPLAIN ANALYZE, and optimizing Django ORM with select_related and prefetch_related to eliminate N+1 bottlenecks.',
    features: [
      'PostgreSQL Schema Normalization & Foreign Keys',
      'Query Optimization with select_related / prefetch_related',
      'Composite & Partial B-Tree Indexes',
      'Data Integrity & Strict Constraints',
    ],
    deliverables: [
      'Optimized Django Models & Migration Files',
      'Query Profiling & Benchmark Reports',
      'Schema Entity-Relationship Documentation',
    ],
    technologies: ['PostgreSQL', 'Django ORM', 'SQL', 'pg_stat_statements'],
    visibility: 'Published',
    featured: true,
  },
  {
    id: 'srv-3',
    order: 3,
    title: 'Authentication & Role-Based Access Control (RBAC)',
    slug: 'authentication-rbac-security',
    icon: 'ShieldCheck',
    shortSummary: 'Stateless token issuance, JWT refresh rotation, secure cookie transport, and granular permissions for multi-role platforms.',
    detailedScope: 'Implementing robust security layers using SimpleJWT, custom permission classes, token refresh blacklisting, and role-based access control protecting administrative endpoints.',
    features: [
      'JWT Authentication with Access/Refresh Tokens',
      'Role-Based Permissions (Buyer, Seller, Admin)',
      'Token Blacklisting & Session Invalidation',
      'Password Hashing (Argon2 / PBKDF2) & Rate Limiting',
    ],
    deliverables: [
      'Custom DRF Permission Classes',
      'Secure Authentication Pipeline Endpoints',
      'Security Audit Checklist',
    ],
    technologies: ['JWT', 'Django REST Framework', 'Python', 'Security'],
    visibility: 'Published',
    featured: true,
  },
  {
    id: 'srv-4',
    order: 4,
    title: 'Payment Gateway Integrations (Khalti & eSewa)',
    slug: 'payment-gateway-integrations',
    icon: 'CreditCard',
    shortSummary: 'Idempotent payment pipelines for Khalti, eSewa, and Stripe with HMAC webhook verification and failure-safe reconciliation.',
    detailedScope: 'End-to-end integration of Nepalese and international payment gateways. Includes automated payment verification calls, idempotency keys to prevent double-crediting, and webhook handling.',
    features: [
      'Khalti ePayment API Integration',
      'eSewa Pay Gateway Integration',
      'Idempotent Transaction Recording',
      'Webhook Verification & Signature Validation',
    ],
    deliverables: [
      'Payment Gateway Integration Module',
      'Sandbox Test Verification Scripts',
      'Transaction History & Ledger Models',
    ],
    technologies: ['Khalti API', 'eSewa API', 'Python', 'Django', 'Stripe'],
    visibility: 'Published',
    featured: true,
  },
  {
    id: 'srv-5',
    order: 5,
    title: 'Full-Stack Web Development (React & Django)',
    slug: 'fullstack-web-development',
    icon: 'Globe',
    shortSummary: 'End-to-end web applications pairing fast React/Vite frontends with robust Django REST backends and Tailwind styling.',
    detailedScope: 'Connecting responsive, accessible React frontends to robust Django APIs. State management, clean data fetching with Axios/Fetch, error handling, and mobile-friendly layouts.',
    features: [
      'Modern React with TypeScript & Vite',
      'Tailwind CSS Utility Styling',
      'Axios Interceptors for JWT Refresh Tokens',
      'Responsive Mobile-First Interfaces',
    ],
    deliverables: [
      'Integrated Full-Stack Repository',
      'Frontend Production Build Bundles',
      'Environment Configuration (.env.example)',
    ],
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Django', 'Vite'],
    visibility: 'Published',
    featured: false,
  },
  {
    id: 'srv-6',
    order: 6,
    title: 'Docker Containerization & Deployment',
    slug: 'docker-deployment',
    icon: 'Cpu',
    shortSummary: 'Production Docker setups, Gunicorn/WhiteNoise configuration, and cloud deployments on Render, Railway, or VPS.',
    detailedScope: 'Creating reproducible multi-container setups using Docker and Docker Compose for Django, PostgreSQL, and Redis. Configuring static file serving with WhiteNoise and production WSGI servers.',
    features: [
      'Docker Compose for Local & Production Parity',
      'Gunicorn WSGI Configuration with Multiple Workers',
      'WhiteNoise Static File Compression & Caching',
      'Zero-Downtime Deployment Configuration',
    ],
    deliverables: [
      'Dockerfile & docker-compose.yml Manifests',
      'Production Deployment Instructions',
      'Database Backup & Restore Scripts',
    ],
    technologies: ['Docker', 'Docker Compose', 'Gunicorn', 'Render', 'Linux'],
    visibility: 'Published',
    featured: false,
  },
];

export const initialArticles: AdminArticle[] = [
  {
    id: 'art-1',
    title: 'Optimizing Django ORM Queries: How I Cut Database Latency by ~30%',
    slug: 'optimizing-django-orm-queries-latency',
    category: 'Backend Engineering',
    date: 'Sep 15, 2026',
    visibility: 'Published',
    featured: true,
    excerpt: 'A practical deep dive into select_related, prefetch_related, B-Tree database indexing, and query plan profiling on high-volume PostgreSQL datasets.',
    content: `When scaling Django applications in production, unoptimized database access patterns are almost always the first major bottleneck. The classic N+1 query syndrome silently degrades response times from 40ms to several seconds as tables grow into thousands of records.

### 1. Identifying the N+1 Query Anti-Pattern
During my backend work at Sajha Infotech on a student management platform, we audited an academic evaluation endpoint executing dozens of redundant SQL queries for a single HTTP request.

By strategically applying select_related for single-valued foreign keys and prefetch_related with Prefetch objects for reverse relations, we collapsed those queries down to deterministic, batched queries.

### 2. Composite Indexes on High-Cardinality Filter Fields
Creating B-Tree composite indexes matching exact query filter orders reduced sequential table scans significantly into fast index-only scans.

### Key Results
- Median API response times dropped by ~30% under simulated load.
- PostgreSQL server CPU utilization decreased during peak student lookup intervals.`,
    authorName: 'Manoj Khatri',
    authorRole: 'Backend Software Engineer',
    tags: ['Django', 'PostgreSQL', 'Performance', 'Python'],
    readTimeMinutes: 5,
  },
  {
    id: 'art-2',
    title: 'Implementing Idempotent Payment Webhooks for Nepali Gateways (Khalti & eSewa)',
    slug: 'implementing-idempotent-payment-webhooks',
    category: 'FinTech & APIs',
    date: 'Aug 28, 2026',
    visibility: 'Published',
    featured: true,
    excerpt: 'Preventing double-crediting, handling network retries safely, and building reliable payment verification pipelines in Python/Django.',
    content: `Payment gateways make no guarantee that a webhook will be delivered only once. Network retries, timeout reconnections, and gateway failovers mean your server must handle duplicate HTTP POST requests gracefully without ever applying a transaction credit twice.

### The Idempotency Key Pattern
Every transaction event must check a deterministic idempotency token or unique transaction index in PostgreSQL. If the transaction has already been marked as verified, subsequent webhook hits return HTTP 200 OK immediately without re-executing credit logic.

### Database Constraints as the Last Line of Defense
Unique compound database constraints on transaction_reference and status ensure that concurrent worker threads fail safely with integrity exceptions rather than causing financial discrepancy.`,
    authorName: 'Manoj Khatri',
    authorRole: 'Backend Software Engineer',
    tags: ['Khalti', 'eSewa', 'Django', 'APIs', 'Security'],
    readTimeMinutes: 4,
  },
  {
    id: 'art-3',
    title: 'Designing Role-Based Access Control (RBAC) with Django REST Framework & JWT',
    slug: 'designing-rbac-django-rest-framework-jwt',
    category: 'Security & Auth',
    date: 'Aug 10, 2026',
    visibility: 'Published',
    featured: false,
    excerpt: 'Structuring multi-role authorization hierarchies with custom DRF permission classes and stateless JSON Web Tokens.',
    content: `In multi-vendor marketplace applications like AgriTech, farmers, buyers, and administrators interact with fundamentally different scopes of data. Structuring clean permissions at the viewset and model level ensures that users cannot tamper with resources outside their authorized tenant or role.`,
    authorName: 'Manoj Khatri',
    authorRole: 'Backend Software Engineer',
    tags: ['Django REST Framework', 'JWT', 'RBAC', 'Python'],
    readTimeMinutes: 4,
  },
  {
    id: 'art-4',
    title: 'Dockerizing Python & Django Applications for Zero-Downtime Deployments',
    slug: 'dockerizing-python-django-applications',
    category: 'DevOps & Deployment',
    date: 'Jul 22, 2026',
    visibility: 'Published',
    featured: false,
    excerpt: 'Multi-stage Dockerfiles, non-root user permissions, Gunicorn worker sizing, and static asset compression with WhiteNoise.',
    content: `Building reproducible container environments ensures that local development accurately mirrors production servers. By pairing Gunicorn with WhiteNoise, Python applications can serve static assets directly with aggressive caching headers without requiring complex external reverse proxies for small-to-medium deployments.`,
    authorName: 'Manoj Khatri',
    authorRole: 'Backend Software Engineer',
    tags: ['Docker', 'Gunicorn', 'Render', 'DevOps'],
    readTimeMinutes: 3,
  },
];

export const initialInquiries: AdminInquiry[] = [
  {
    id: 'inq-1',
    name: 'Aarav Sharma',
    company: 'AgriCommerce Kathmandu',
    email: 'aarav.sharma@agricommerce.np',
    phone: '+977 9851023456',
    hasWhatsApp: true,
    scopeTitle: 'Backend REST API & Khalti Integration',
    budgetRange: 'NPR 100,000–200,000 (~US$750–1,500)',
    timeline: '1–2 Months',
    message: 'Hi Manoj, we saw your AgriTech marketplace project on GitHub. We are building an organic vegetable ordering platform in Kathmandu and need a skilled Python/Django developer to build our REST API, JWT authentication, and Khalti payment verification module. Are you available for freelance work?',
    submittedAt: 'Sep 12, 2026, 8:02 AM',
    status: 'Closed',
    read: true,
    replied: true,
  },
  {
    id: 'inq-2',
    name: 'Bikash Adhikari',
    company: 'Tech Solutions Nepal',
    email: 'bikash.adhikari@techsolutions.com.np',
    phone: '+977 9841897654',
    hasWhatsApp: true,
    scopeTitle: 'Backend Software Engineer Role (Django / PostgreSQL)',
    budgetRange: 'Full-time / Contract',
    timeline: 'Immediate',
    message: 'Hello Manoj, our engineering team is reviewing your profile and projects (specifically your query optimization work at Sajha Infotech and your BIT background). We have an open Junior Backend Software Engineer position focusing on Django REST Framework and PostgreSQL. Would you be open to an introductory interview this week?',
    submittedAt: 'Sep 18, 2026, 11:45 AM',
    status: 'In Progress',
    read: true,
    replied: true,
  },
  {
    id: 'inq-3',
    name: 'Sarah Jenkins',
    company: 'Nexus Digital Co.',
    email: 'sarah.j@nexusdigital.io',
    phone: '+1 (415) 890-3421',
    hasWhatsApp: true,
    scopeTitle: 'PostgreSQL Query Optimization & API Consulting',
    budgetRange: 'US$800–$1,500',
    timeline: '2–3 Weeks',
    message: 'Hi Manoj, we came across your technical article on Django ORM optimization and query indexing. We have an existing DRF application with latency spikes on our main dashboard queries. We would like to hire you for a consultation and audit to profile our execution plans and optimize our indexes.',
    submittedAt: 'Sep 20, 2026, 3:15 AM',
    status: 'New',
    read: false,
    replied: false,
  },
];

export const initialHomepageContent: HomepageContentState = {
  heroHeading: 'Manoj Khatri',
  heroTagline: 'Backend Software Engineer · Python, Django, DRF & PostgreSQL',
  heroDescription: 'Python/Django backend developer based in Kathmandu, Nepal, focused on building secure server-side systems that power real products. Specializing in Django REST Framework, PostgreSQL, JWT authentication, role-based access control, and payment gateway integrations.',
  primaryCtaText: 'View Projects',
  primaryCtaLink: '#projects',
  secondaryCtaText: 'Get In Touch',
  secondaryCtaLink: '#contact',
  aboutSummaryBlock: 'I build clean, reliable, production-ready server-side applications. My experience spans designing normalized database schemas, optimizing queries to reduce latency, and shipping secure REST APIs.',
  servicesSectionHeading: 'Core Competencies & Services',
  servicesSectionSubtitle: 'From robust backend systems to optimized database schemas and payment pipelines.',
  bottomCtaHeading: 'Looking for a Backend Software Engineer?',
  bottomCtaDescription: 'I am open to remote freelance contracts, API development projects, and junior backend software engineer roles.',
  bottomCtaButtonLabel: 'Send a Message',
  bottomCtaButtonLink: '#contact',
};

export const initialAboutContent: AboutContentState = {
  heading: 'Backend Software Engineer with Production Focus',
  subtitle: 'Building reliable server-side systems, optimized databases, and clean REST APIs.',
  introParagraph: "I'm a Python/Django backend developer based in Kathmandu, Nepal, focused on building secure server-side systems that power real products. My work centers on Django REST Framework, PostgreSQL, JWT authentication, role-based access control, and payment gateway integrations like Khalti and eSewa.",
  backgroundStory: "I hold a BIT from Tribhuvan University (2025) and completed hands-on backend training at Sajha Infotech, where I cut average API response times by ~30% through query optimization on an enterprise student management system. Currently deepening Celery, Docker, and API architecture for scalable systems.",
  mission: 'To write clean, reliable, well-tested backend services that provide seamless experiences for users and fellow developers alike.',
  vision: 'To engineer robust distributed backends and high-availability APIs for impactful web and mobile platforms across Nepal and globally.',
  principles: [
    {
      id: 'pr-1',
      title: 'Clean Architecture',
      description: 'Clear separation of concerns between models, serializers, views, and business services for maintainability and testing.',
    },
    {
      id: 'pr-2',
      title: 'Security by Default',
      description: 'Role-based authorization, JWT token rotation, input sanitization, and OWASP principles applied across every endpoint.',
    },
    {
      id: 'pr-3',
      title: 'Database Performance',
      description: 'Profiling query execution plans, eliminating N+1 queries, and applying thoughtful B-Tree indexes for sub-100ms speeds.',
    },
    {
      id: 'pr-4',
      title: 'Production Readiness',
      description: 'Containerized with Docker, environment variable isolation, and complete Postman/OpenAPI documentation.',
    },
  ],
  metrics: [
    {
      id: 'm-1',
      value: 'Kathmandu',
      label: 'Location',
      helperNote: 'Nepal (Open to Remote)',
    },
    {
      id: 'm-2',
      value: '~30%',
      label: 'API Query Speedup',
      helperNote: 'At Sajha Infotech',
    },
    {
      id: 'm-3',
      value: 'BIT',
      label: 'Degree (2025)',
      helperNote: 'Tribhuvan University',
    },
    {
      id: 'm-4',
      value: '100%',
      label: 'Production Focus',
      helperNote: 'Clean APIs & tested code',
    },
  ],
};

export const initialContactPricing: ContactPricingState = {
  officialEmail: 'manojkc1dev@gmail.com',
  primaryPhone: '+977 9842203976',
  whatsappPhone: '+977 9842203976',
  whatsappDirectLink: 'https://wa.me/9779842203976',
  officeAddress: 'Kathmandu, Nepal',
  cityCountry: 'Kathmandu, Nepal',
  locationStatement: 'Based in Kathmandu, Nepal · Open to Remote & Local Roles',
  workingHours: 'Sunday – Friday: 9:00 AM – 6:00 PM NPT (UTC+5:45)',
  indicativeBudgetStatement: 'Open to full-time junior backend roles, freelance API development, and technical consulting.',
  budgetTiers: `NPR 25,000 – NPR 50,000 (Feature / Integration)
NPR 50,000 – NPR 100,000 (MVP REST API Suite)
NPR 100,000 – NPR 200,000 (Full-Stack / Marketplace Backend)
Full-Time / Retainer (Negotiable based on role)`,
  timelineOptions: `1 – 2 Weeks (API Integration / Bug Fixes)
2 – 4 Weeks (MVP Backend System)
1 – 2 Months (Complete Full-Stack Application)
Full-Time Employment (Immediate Availability)`,
  projectTypes: `Django REST Framework API Development
PostgreSQL Schema Design & Query Optimization
Payment Gateway Integration (Khalti / eSewa)
Authentication & RBAC Setup (JWT)
Full-Stack Web App (React + Django)
Junior Backend Software Engineer (Full-Time)`,
};

export const initialFooterContent: FooterContentState = {
  companyDescription: 'Manoj Khatri is a Kathmandu-based Backend Software Engineer specializing in Python, Django REST Framework, PostgreSQL, and scalable API design.',
  primaryMarket: 'Nepal',
  targetMarkets: 'Kathmandu · Nepal · Global Remote',
  locationStatement: 'Based in Kathmandu, Nepal · Open to Remote Opportunities',
  copyright: '© 2026 Manoj Khatri. All rights reserved.',
  navigationLinks: [
    { id: 'fl-1', title: 'Projects', url: '#projects', category: 'Solutions', visible: true },
    { id: 'fl-2', title: 'Skills & Stack', url: '#skills', category: 'Solutions', visible: true },
    { id: 'fl-3', title: 'Experience', url: '#experience', category: 'Solutions', visible: true },
    { id: 'fl-4', title: 'Services', url: '#services', category: 'Solutions', visible: true },
    { id: 'fl-5', title: 'About Manoj', url: '#about', category: 'Company', visible: true },
    { id: 'fl-6', title: 'Contact', url: '#contact', category: 'Company', visible: true },
    { id: 'fl-7', title: 'GitHub', url: 'https://github.com/manojkc1dev', category: 'Company', visible: true },
    { id: 'fl-8', title: 'LinkedIn', url: 'https://linkedin.com/in/manojkc1dev', category: 'Company', visible: true },
  ],
};

export const initialLogoManagement: LogoManagementState = {
  logoUrl: '/icons/favicon-32x32.png',
  altText: 'Manoj Khatri portfolio icon',
};

export const initialCompanyIdentity: CompanyIdentityState = {
  companyName: 'Manoj Khatri',
  slogan: 'Clean architecture. Reliable APIs. Production-ready code.',
  shortDescription: 'Backend Software Engineer specializing in Python, Django REST Framework, and PostgreSQL.',
  fullDescription: 'Manoj Khatri is a backend software engineer based in Kathmandu, Nepal, specializing in building secure REST APIs, role-based access control systems, and payment gateway integrations.',
  primaryMarket: 'Nepal',
  targetMarketsFormatted: 'Kathmandu · Nepal · Global Remote',
  internationalCountries: 'Nepal, Remote Global',
};

export const initialSocialProfiles: SocialProfile[] = [
  { id: 'soc-1', platform: 'LinkedIn', url: 'https://linkedin.com/in/manojkc1dev', visible: true },
  { id: 'soc-2', platform: 'GitHub', url: 'https://github.com/manojkc1dev', visible: true },
  { id: 'soc-3', platform: 'X / Twitter', url: 'https://x.com/manojkc1dev', visible: true },
  { id: 'soc-4', platform: 'Facebook', url: 'https://facebook.com/manojkc1dev', visible: true },
  { id: 'soc-5', platform: 'WhatsApp', url: 'https://wa.me/9779842203976', visible: true },
];

export const initialGlobalSettings: GlobalSettingsState = {
  entityName: 'Manoj Khatri',
  tagline: 'Backend Software Engineer | Python, Django, DRF',
  primaryDomesticMarket: 'Nepal',
  targetInternationalMarkets: 'Kathmandu · Nepal · Global Remote',
  siteTitleTemplate: 'Manoj Khatri | Backend Software Engineer',
  metaDescription: 'Manoj Khatri is a Python/Django backend engineer in Kathmandu, Nepal, building secure REST APIs with DRF, PostgreSQL, JWT auth, and Khalti/eSewa payment integrations.',
  keywords: 'Manoj Khatri, Backend Software Engineer, Python Django Developer Kathmandu, DRF, PostgreSQL, Khalti integration, eSewa, AgriTech, Sajha Infotech',
};

export const initialSiteContent = {
  heroBadge: 'PYTHON / DJANGO BACKEND SOFTWARE ENGINEER',
  heroTitle: 'Clean Architecture. Reliable APIs. Production-Ready Code.',
  heroSubtitle: 'Manoj Khatri is a Python/Django backend engineer based in Kathmandu, Nepal, specializing in Django REST Framework, PostgreSQL query optimization, JWT authentication, and Khalti/eSewa integrations.',
  primaryCta: 'Explore Projects',
  secondaryCta: 'Get In Touch',
  stats: [
    {
      value: '4+',
      label: 'Shipped Systems',
      description: 'Production web applications, APIs, and student ERP platforms.',
    },
    {
      value: '~30%',
      label: 'Query Latency Reduction',
      description: 'Optimized PostgreSQL queries and Django ORM access patterns at Sajha Infotech.',
    },
    {
      value: '10,000+',
      label: 'Bilingual Entries',
      description: 'Unicode-indexed dictionary entries in Shabdhabhandar.',
    },
    {
      value: 'BIT',
      label: 'Tribhuvan University (2025)',
      description: 'Bachelor of Information Technology graduate.',
    },
  ],
  pillars: [
    {
      title: 'Clean Architecture & API Reliability',
      description: 'Structuring clear service boundaries, validated serializers, and predictable error contracts.',
      focus: 'Reliability',
    },
    {
      title: 'Sub-Second Database Performance',
      description: 'Eliminating N+1 queries, composite B-Tree indexes, and profiling execution plans.',
      focus: 'Performance',
    },
    {
      title: 'Cryptographic Security & RBAC',
      description: 'JWT token rotation, role-based authorization, and idempotent payment webhook handling.',
      focus: 'Security',
    },
    {
      title: 'Tested Code & Clean Handover',
      description: 'Automated test coverage, Postman API collections, and containerized Docker setups.',
      focus: 'Code Quality',
    },
  ],
  contactLocation: 'Kathmandu, Nepal',
  contactEmail: 'manojkc1dev@gmail.com',
  contactPhone: '+977 9842203976',
  whatsappLink: 'https://wa.me/9779842203976',
  githubLink: 'https://github.com/manojkc1dev',
  linkedinLink: 'https://linkedin.com/in/manojkc1dev',
};

export const initialResumeData: ResumeData = {
  resumeUrl: '/resume.pdf',
  fileName: 'Manoj_KC_Backend_Engineer_Resume.pdf',
  versionTag: 'v2026.3 · Updated March 2026',
  targetHeadline: 'Backend Software Engineer · Python, Django, DRF & PostgreSQL Specialist',
  summaryText:
    'Dedicated Python/Django backend engineer with real-world experience designing normalized PostgreSQL schemas, building secure RESTful APIs with Django REST Framework, and optimizing database queries (~30% latency reduction at Sajha Infotech). Skilled in JWT authentication, granular role-based access control, Celery async queues, Redis, and idempotent payment gateway integrations (Khalti & eSewa).',
  sections: [
    {
      id: 'sec-exp',
      title: 'Work Experience',
      category: 'experience',
      description: 'Production backend development and database engineering roles.',
      items: [
        {
          id: 'item-exp-1',
          title: 'Junior Backend Software Engineer',
          subtitle: 'Sajha Infotech Pvt. Ltd.',
          location: 'Kathmandu, Nepal',
          period: 'Jul 2025 – Present',
          badge: 'Current Role',
          description:
            'Leading core backend module development and database optimization for enterprise software solutions.',
          bullets: [
            'Optimized PostgreSQL query execution plans using EXPLAIN ANALYZE, eliminating N+1 bottlenecks and reducing average response times by ~30%.',
            'Engineered RESTful API endpoints using Django REST Framework for student management and academic evaluation systems handling 5,000+ records.',
            'Implemented stateless JWT token authentication with rotating refresh tokens and fine-grained role-based permission classes (RBAC).',
            'Integrated automated background jobs with Celery and Redis for report generation and bulk notification dispatches.',
          ],
        },
        {
          id: 'item-exp-2',
          title: 'Freelance Backend & API Developer',
          subtitle: 'Self-Employed / Independent Contractor',
          location: 'Remote / Nepal',
          period: 'Jan 2024 – Jun 2025',
          description:
            'Delivered custom web applications, REST APIs, and third-party integrations for small businesses and developer communities.',
          bullets: [
            'Architected PayStream: Unified payment gateway microservice with idempotent transaction recording and HMAC signature verification for eSewa EPAY v2 and Khalti v2.',
            'Developed AgriTech Marketplace backend with automated product catalogs, stock tracking, and merchant administration portals.',
            'Solo-engineered AcadFlow SMS BIT capstone project with automated server-side PDF report card compilation via ReportLab.',
          ],
        },
      ],
    },
    {
      id: 'sec-edu',
      title: 'Education & Credentials',
      category: 'education',
      description: 'Formal academic degree and computer science foundations.',
      items: [
        {
          id: 'item-edu-1',
          title: 'Bachelor of Information Technology (BIT)',
          subtitle: 'Mahendra Multiple Campus, Tribhuvan University',
          location: 'Nepal',
          period: '2021 – 2025',
          badge: 'First Division Honors',
          description:
            'Graduated with First Division honors focusing on software engineering, database systems, and distributed architecture.',
          bullets: [
            'Core Coursework: Relational Database Management Systems, Data Structures & Algorithms, Object-Oriented Programming, Computer Networks, Operating Systems, Web Technologies.',
            'Final Year Capstone Project: AcadFlow SMS — Full-stack institutional management platform built with Python, Django, PostgreSQL, and ReportLab PDF engine.',
          ],
        },
      ],
    },
    {
      id: 'sec-cert',
      title: 'Certifications & Specialized Training',
      category: 'certifications',
      description: 'Verified professional certifications and technical courses.',
      items: [
        {
          id: 'item-cert-1',
          title: 'Python & Django Backend Architecture',
          subtitle: 'Sajha Infotech Professional Training',
          period: '2025',
          badge: 'Verified',
          description:
            'Advanced practical training covering DRF serializers, viewsets, query optimization, Celery, and production deployment with Docker.',
        },
        {
          id: 'item-cert-2',
          title: 'PostgreSQL Query Profiling & Performance Tuning',
          subtitle: 'Database Systems Specialization',
          period: '2025',
          badge: 'Verified',
          description:
            'In-depth mastery of B-Tree indexing, composite indexes, query planner statistics, and connection pool management with PgBouncer.',
        },
        {
          id: 'item-cert-3',
          title: 'REST API Security & Idempotency Pipelines',
          subtitle: 'Fintech & Web Security Architecture',
          period: '2024',
          badge: 'Verified',
          description:
            'Implementing token blacklisting, HMAC-SHA256 signature verification, replay attack prevention, and idempotent retry queues.',
        },
      ],
    },
    {
      id: 'sec-skills',
      title: 'Core Technical Competencies',
      category: 'skills',
      description: 'Languages, frameworks, databases, and DevOps tooling.',
      items: [
        {
          id: 'item-skill-1',
          title: 'Languages & Core Systems',
          subtitle: 'Python 3.12, SQL (PostgreSQL), TypeScript, JavaScript, HTML5, CSS3',
          description: 'Strong object-oriented programming, typed codebases, and relational query structuring.',
        },
        {
          id: 'item-skill-2',
          title: 'Frameworks & Libraries',
          subtitle: 'Django 5.x, Django REST Framework (DRF), Celery, Redis, FastAPI, Tailwind CSS',
          description: 'Production web application architecture and asynchronous task processing.',
        },
        {
          id: 'item-skill-3',
          title: 'Databases & Performance',
          subtitle: 'PostgreSQL, SQLite, Redis Caching, EXPLAIN ANALYZE, Connection Pooling',
          description: 'Normalized 3NF relational schemas, composite indexes, and low-latency query tuning.',
        },
        {
          id: 'item-skill-4',
          title: 'DevOps & Tooling',
          subtitle: 'Docker, Docker Compose, Git/GitHub, Linux/Bash, Gunicorn, WhiteNoise, Postman',
          description: 'Reproducible local environments, CI/CD pipelines, and cloud hosting on Render and VPS.',
        },
      ],
    },
  ],
};

