# Generated by Django 5.2.16 on 2026-07-26 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Section"),
                            ("about", "About Section"),
                            ("skills", "Skills Section"),
                            ("techstack", "Tech Stack Section"),
                            ("projects", "Featured Projects"),
                            ("experience", "Experience Section"),
                            ("education", "Education Section"),
                            ("certifications", "Certifications Section"),
                            ("services", "Services Section"),
                            ("testimonials", "Testimonials Section"),
                            ("clients", "Clients Section"),
                            ("blog", "Latest Blog Posts"),
                            ("contact", "Contact Section"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("custom_title", models.CharField(blank=True, max_length=255)),
                (
                    "display_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Limit number of items to display",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homepage Section",
                "verbose_name_plural": "Homepage Sections",
                "db_table": "homepage_sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("site_name", models.CharField(default="Portfolio", max_length=100)),
                ("tagline", models.CharField(blank=True, max_length=255)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="settings/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="settings/"),
                ),
                (
                    "default_theme",
                    models.CharField(
                        choices=[
                            ("dark", "Dark Mode"),
                            ("light", "Light Mode"),
                            ("system", "System Default"),
                        ],
                        default="dark",
                        max_length=10,
                    ),
                ),
                ("allow_theme_toggle", models.BooleanField(default=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("github_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("footer_text", models.TextField(blank=True)),
                (
                    "copyright_text",
                    models.CharField(
                        default="© {year} All rights reserved", max_length=255
                    ),
                ),
                ("show_social_links", models.BooleanField(default=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                ("google_analytics_id", models.CharField(blank=True, max_length=50)),
                ("posthog_api_key", models.CharField(blank=True, max_length=100)),
                ("posthog_host", models.URLField(blank=True)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("maintenance_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
                "db_table": "site_settings",
            },
        ),
    ]
